export async function POST(req: Request) {
    const { prompt } = await req.json();
  
    return Response.json({
      nodes: [
        {
          type: 'newsNode',
          data: {
            title: `Related to "${prompt}"`,
            summary: 'Generated by AI',
            image: '/images/file.svg',
            url: '#',
            reactions: {
              shareholder: { sentiment: 'positive', comment: 'Great news!' },
              bank: { sentiment: 'neutral', comment: 'Interesting perspective.' },
              partner: { sentiment: 'negative', comment: 'Not sure about this.' },
              client: { sentiment: 'positive', comment: 'Exciting development!' },
            },
          },
        },
      ],
      edges: [], // Optional: empty, or pre-wired
    });
  }
  